services:
  - type: web
    name: skyscraper-bot-api
    env: python
    region: oregon
    plan: starter
    buildCommand: "pip install fastapi uvicorn httpx pydantic requests pandas openai anthropic python-dotenv cryptography python-json-logger click gunicorn"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4"
    repo: https://github.com/goryckikukasz-skyscraper/skyscraper-backend
    branch: main
    healthCheckPath: /v1/health
    autoDeploy: true

  - type: redis
    name: skyscraper-redis
    region: oregon
    plan: starter

databases:
  - name: skyscraper-db
    region: oregon
    plan: starter
    databaseName: skyscraper_prod
    user: skyscraper_user
